[project]
name = "qiskit-mcp-server"
version = "0.1.0"
description = "MCP server for Qiskit quantum computing SDK"
readme = "README.md"
requires-python = ">=3.10,<4.0"
dependencies = [
    "fastmcp>=2.8.1",
    "qiskit>=1.0.0",
    "qiskit-aer>=0.13.0",
    "python-dotenv>=1.0.0",
    "nest-asyncio>=1.5.0",
    "pydantic>=2.0.0",
    "matplotlib>=3.5.0",
]

[[project.authors]]
name = "Quantum+AI Team. IBM Quantum"
email = "Quantum.Plus.AI@ibm.com"

[project.license]
text = "Apache-2.0"

keywords = ["quantum", "qiskit", "mcp", "ai", "quantum-computing", "sdk"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Scientific/Engineering :: Physics",
    "Topic :: Software Development :: Libraries :: Python Modules",
]

[project.urls]
Homepage = "https://github.com/Qiskit/qiskit-mcp-servers"
Repository = "https://github.com/Qiskit/qiskit-mcp-servers"
Documentation = "https://github.com/Qiskit/qiskit-mcp-servers/tree/main/qiskit-mcp-server#readme"
"Bug Tracker" = "https://github.com/Qiskit/qiskit-mcp-servers/issues"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project.scripts]
qiskit-mcp-server = "qiskit_mcp_server:main"

[dependency-groups]
dev = [
    "ruff>=0.11.13",
    "mypy>=1.15.0",
]
test = [
    "pytest>=7.4.0",
    "pytest-asyncio>=0.21.0",
    "pytest-mock>=3.11.0",
    "pytest-cov>=4.1.0",
]
