name: Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test-code-assistant:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"
    
    - name: Set up Python ${{ matrix.python-version }}
      run: uv python install ${{ matrix.python-version }}
    
    - name: Install dependencies for Code Assistant server
      working-directory: ./qiskit-code-assistant-mcp-server
      run: |
        uv sync --group dev --group test
    
    - name: Run linting for Code Assistant server
      working-directory: ./qiskit-code-assistant-mcp-server
      run: |
        uv run ruff check src tests
        uv run ruff format --check src tests
    
    - name: Run type checking for Code Assistant server
      working-directory: ./qiskit-code-assistant-mcp-server
      run: |
        uv run mypy src
    
    - name: Run tests for Code Assistant server
      working-directory: ./qiskit-code-assistant-mcp-server
      run: |
        uv run pytest tests/ -v --cov=src --cov-report=xml --cov-report=term-missing
    
    - name: Upload coverage for Code Assistant server
      uses: codecov/codecov-action@v3
      with:
        file: ./qiskit-code-assistant-mcp-server/coverage.xml
        flags: code-assistant
        name: code-assistant-coverage

  test-runtime:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"
    
    - name: Set up Python ${{ matrix.python-version }}
      run: uv python install ${{ matrix.python-version }}
    
    - name: Install dependencies for Runtime server
      working-directory: ./qiskit-ibm-runtime-mcp-server
      run: |
        uv sync --group dev --group test
    
    - name: Run linting for Runtime server
      working-directory: ./qiskit-ibm-runtime-mcp-server
      run: |
        uv run ruff check src tests
        uv run ruff format --check src tests
    
    - name: Run type checking for Runtime server
      working-directory: ./qiskit-ibm-runtime-mcp-server
      run: |
        uv run mypy src
    
    - name: Run tests for Runtime server
      working-directory: ./qiskit-ibm-runtime-mcp-server
      run: |
        uv run pytest tests/ -v --cov=src --cov-report=xml --cov-report=term-missing
    
    - name: Upload coverage for Runtime server
      uses: codecov/codecov-action@v3
      with:
        file: ./qiskit-ibm-runtime-mcp-server/coverage.xml
        flags: runtime
        name: runtime-coverage